=== nathanaelbayle/C5-260121-INFO/musique.dtd
<!ELEMENT musique (cd*)>
<!ELEMENT cd (titre, artiste?, groupe?, chanson*)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT groupe (#PCDATA)>
<!ELEMENT artiste (nom, prenom)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT chanson (#PCDATA)>
<!ATTLIST chanson duree CDATA #IMPLIED>

=== nathanaelbayle/C5-260121-INFO/TP1/musique.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE musique SYSTEM "musique.dtd">
<musique>
    <cd>
        <titre>It's a wonderful life</titre>
        <groupe>Sparklehorse</groupe>
        <chanson>Eyepennies</chanson>
        <chanson>Dog door</chanson>
        <chanson/>
    </cd>
    <cd>
        <titre>BOF le fabuleux destin ... </titre>
        <artiste>
            <nom>Tiersen</nom>
            <prenom>Yann</prenom>
        </artiste>
        <chanson>A quai</chanson>
        <chanson duree='3:40'>Comptine d'un autre été</chanson>
    </cd>
</musique>
