=== nathanaelbayle/C5-260121-INFO/TP2/mediatheque.dtd
<!ELEMENT mediatheque (musique, video)>
<!ELEMENT musique (contenu, cd+)>
<!ELEMENT cd (titre, ( groupe| artiste), chanson+)>
<!ELEMENT artiste (nom, prenom)>

<!ELEMENT video (dvd*, br)>
<!ELEMENT dvd (titre, annee?, realisateur)>
<!ELEMENT br (titre, annee?, realisateur)>


<!ELEMENT titre (#PCDATA)>
<!ELEMENT chanson (#PCDATA)>
<!ELEMENT groupe (#PCDATA)>
<!ELEMENT contenu (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT annee (#PCDATA)>
<!ELEMENT realisateur (#PCDATA)>


<!ATTLIST mediatheque xmlns CDATA #FIXED "http://media.org">
<!ATTLIST chanson duree CDATA #REQUIRED>
<!ATTLIST cd type (CD|SACD) "CD">

=== nathanaelbayle/C5-260121-INFO/TP2/mediatheque.xml
<?xml version='1.0' standalone="no" ?>
<!DOCTYPE mediatheque SYSTEM "mediatheque.dtd">
<mediatheque xmlns="http://media.org">
 <musique> <!-- partie optionnelle mais a occurrence unique -->
  <contenu> 2 CD de musique assez variee </contenu>
   <cd type="SACD">
   <titre>It's a wonderful life</titre>
   <groupe>Sparklehorse</groupe>
   <chanson duree='00:05:27'>Eyepennies</chanson>
   <chanson duree='00:02:46'>Dog door</chanson>
  </cd>
  <cd>
   <titre>BOF Le fabuleux destin...</titre>
   <artiste>
    <nom>Tiersen</nom>
    <prenom>Yann</prenom>
   </artiste>
   <chanson duree='00:03:54'>A quai</chanson>
   <chanson duree='00:03:40'>Comptine d'un autre ete</chanson>
  </cd>
 </musique>
 <video> <!-- partie optionnelle mais a occurrence unique -->
  <dvd>
   <titre>2001, Odyssee de l'espace</titre>
   <annee>1968</annee>
   <realisateur>S. Kubrick</realisateur>
  </dvd>
  <dvd>
   <titre>Barry Lindon</titre>
   <realisateur>S. Kubrick</realisateur>
  </dvd>
  <br>
   <titre>Les sentiers de la gloire</titre>
   <annee>1957</annee>
   <realisateur>S. Kubrick</realisateur>
  </br>
 </video>
 
</mediatheque>
